// Code generated by protoc-gen-go. DO NOT EDIT.
// source: session.proto

package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Type int32

const (
	Type_STANDARD Type = 0
	Type_PREMIUM  Type = 1
	Type_ADMIN    Type = 2
)

var Type_name = map[int32]string{
	0: "STANDARD",
	1: "PREMIUM",
	2: "ADMIN",
}
var Type_value = map[string]int32{
	"STANDARD": 0,
	"PREMIUM":  1,
	"ADMIN":    2,
}

func (x Type) String() string {
	return proto1.EnumName(Type_name, int32(x))
}
func (Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

type TokenString struct {
	Token string `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
}

func (m *TokenString) Reset()                    { *m = TokenString{} }
func (m *TokenString) String() string            { return proto1.CompactTextString(m) }
func (*TokenString) ProtoMessage()               {}
func (*TokenString) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *TokenString) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type AccountID struct {
	Id uint64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *AccountID) Reset()                    { *m = AccountID{} }
func (m *AccountID) String() string            { return proto1.CompactTextString(m) }
func (*AccountID) ProtoMessage()               {}
func (*AccountID) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *AccountID) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type AccountType struct {
	Type Type `protobuf:"varint,1,opt,name=type,enum=proto.Type" json:"type,omitempty"`
}

func (m *AccountType) Reset()                    { *m = AccountType{} }
func (m *AccountType) String() string            { return proto1.CompactTextString(m) }
func (*AccountType) ProtoMessage()               {}
func (*AccountType) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *AccountType) GetType() Type {
	if m != nil {
		return m.Type
	}
	return Type_STANDARD
}

type Payload struct {
	Id   uint64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Type Type   `protobuf:"varint,2,opt,name=type,enum=proto.Type" json:"type,omitempty"`
}

func (m *Payload) Reset()                    { *m = Payload{} }
func (m *Payload) String() string            { return proto1.CompactTextString(m) }
func (*Payload) ProtoMessage()               {}
func (*Payload) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *Payload) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Payload) GetType() Type {
	if m != nil {
		return m.Type
	}
	return Type_STANDARD
}

type Status struct {
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (m *Status) Reset()                    { *m = Status{} }
func (m *Status) String() string            { return proto1.CompactTextString(m) }
func (*Status) ProtoMessage()               {}
func (*Status) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *Status) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto1.RegisterType((*TokenString)(nil), "proto.TokenString")
	proto1.RegisterType((*AccountID)(nil), "proto.AccountID")
	proto1.RegisterType((*AccountType)(nil), "proto.AccountType")
	proto1.RegisterType((*Payload)(nil), "proto.Payload")
	proto1.RegisterType((*Status)(nil), "proto.Status")
	proto1.RegisterEnum("proto.Type", Type_name, Type_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for SessionService service

type SessionServiceClient interface {
	GetAccountIDFromToken(ctx context.Context, in *TokenString, opts ...grpc.CallOption) (*AccountID, error)
	GetAccountTypeFromToken(ctx context.Context, in *TokenString, opts ...grpc.CallOption) (*AccountType, error)
	CreateToken(ctx context.Context, in *Payload, opts ...grpc.CallOption) (*TokenString, error)
	RefreshToken(ctx context.Context, in *TokenString, opts ...grpc.CallOption) (*TokenString, error)
	DeleteToken(ctx context.Context, in *TokenString, opts ...grpc.CallOption) (*Status, error)
	CheckToken(ctx context.Context, in *TokenString, opts ...grpc.CallOption) (*Status, error)
}

type sessionServiceClient struct {
	cc *grpc.ClientConn
}

func NewSessionServiceClient(cc *grpc.ClientConn) SessionServiceClient {
	return &sessionServiceClient{cc}
}

func (c *sessionServiceClient) GetAccountIDFromToken(ctx context.Context, in *TokenString, opts ...grpc.CallOption) (*AccountID, error) {
	out := new(AccountID)
	err := grpc.Invoke(ctx, "/proto.SessionService/GetAccountIDFromToken", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionServiceClient) GetAccountTypeFromToken(ctx context.Context, in *TokenString, opts ...grpc.CallOption) (*AccountType, error) {
	out := new(AccountType)
	err := grpc.Invoke(ctx, "/proto.SessionService/GetAccountTypeFromToken", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionServiceClient) CreateToken(ctx context.Context, in *Payload, opts ...grpc.CallOption) (*TokenString, error) {
	out := new(TokenString)
	err := grpc.Invoke(ctx, "/proto.SessionService/CreateToken", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionServiceClient) RefreshToken(ctx context.Context, in *TokenString, opts ...grpc.CallOption) (*TokenString, error) {
	out := new(TokenString)
	err := grpc.Invoke(ctx, "/proto.SessionService/RefreshToken", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionServiceClient) DeleteToken(ctx context.Context, in *TokenString, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := grpc.Invoke(ctx, "/proto.SessionService/DeleteToken", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionServiceClient) CheckToken(ctx context.Context, in *TokenString, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := grpc.Invoke(ctx, "/proto.SessionService/CheckToken", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for SessionService service

type SessionServiceServer interface {
	GetAccountIDFromToken(context.Context, *TokenString) (*AccountID, error)
	GetAccountTypeFromToken(context.Context, *TokenString) (*AccountType, error)
	CreateToken(context.Context, *Payload) (*TokenString, error)
	RefreshToken(context.Context, *TokenString) (*TokenString, error)
	DeleteToken(context.Context, *TokenString) (*Status, error)
	CheckToken(context.Context, *TokenString) (*Status, error)
}

func RegisterSessionServiceServer(s *grpc.Server, srv SessionServiceServer) {
	s.RegisterService(&_SessionService_serviceDesc, srv)
}

func _SessionService_GetAccountIDFromToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TokenString)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServiceServer).GetAccountIDFromToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.SessionService/GetAccountIDFromToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServiceServer).GetAccountIDFromToken(ctx, req.(*TokenString))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionService_GetAccountTypeFromToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TokenString)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServiceServer).GetAccountTypeFromToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.SessionService/GetAccountTypeFromToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServiceServer).GetAccountTypeFromToken(ctx, req.(*TokenString))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionService_CreateToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Payload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServiceServer).CreateToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.SessionService/CreateToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServiceServer).CreateToken(ctx, req.(*Payload))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionService_RefreshToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TokenString)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServiceServer).RefreshToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.SessionService/RefreshToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServiceServer).RefreshToken(ctx, req.(*TokenString))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionService_DeleteToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TokenString)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServiceServer).DeleteToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.SessionService/DeleteToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServiceServer).DeleteToken(ctx, req.(*TokenString))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionService_CheckToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TokenString)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServiceServer).CheckToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.SessionService/CheckToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServiceServer).CheckToken(ctx, req.(*TokenString))
	}
	return interceptor(ctx, in, info, handler)
}

var _SessionService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.SessionService",
	HandlerType: (*SessionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAccountIDFromToken",
			Handler:    _SessionService_GetAccountIDFromToken_Handler,
		},
		{
			MethodName: "GetAccountTypeFromToken",
			Handler:    _SessionService_GetAccountTypeFromToken_Handler,
		},
		{
			MethodName: "CreateToken",
			Handler:    _SessionService_CreateToken_Handler,
		},
		{
			MethodName: "RefreshToken",
			Handler:    _SessionService_RefreshToken_Handler,
		},
		{
			MethodName: "DeleteToken",
			Handler:    _SessionService_DeleteToken_Handler,
		},
		{
			MethodName: "CheckToken",
			Handler:    _SessionService_CheckToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "session.proto",
}

func init() { proto1.RegisterFile("session.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 331 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x90, 0x4f, 0x4f, 0xc2, 0x40,
	0x10, 0xc5, 0xa5, 0xe1, 0xef, 0x14, 0x9a, 0x66, 0xa2, 0x91, 0xe0, 0x41, 0x53, 0x2f, 0xc6, 0x18,
	0x54, 0x4c, 0x3c, 0x98, 0x78, 0x68, 0xa8, 0x1a, 0x0e, 0x10, 0xb2, 0xc5, 0x0f, 0x50, 0xcb, 0x28,
	0x0d, 0xd8, 0x25, 0xbb, 0x8b, 0x09, 0xdf, 0xd6, 0x8f, 0x62, 0xd8, 0x2e, 0x54, 0x0d, 0xfe, 0x39,
	0x35, 0xb3, 0x6f, 0x7e, 0x6f, 0x5e, 0x1f, 0x34, 0x24, 0x49, 0x99, 0xf0, 0xb4, 0x3d, 0x17, 0x5c,
	0x71, 0x2c, 0xe9, 0x8f, 0x77, 0x0c, 0xf6, 0x88, 0x4f, 0x29, 0x0d, 0x95, 0x48, 0xd2, 0x17, 0xdc,
	0x85, 0x92, 0x5a, 0x8d, 0xcd, 0xc2, 0x51, 0xe1, 0xa4, 0xc6, 0xb2, 0xc1, 0x3b, 0x80, 0x9a, 0x1f,
	0xc7, 0x7c, 0x91, 0xaa, 0x5e, 0x80, 0x0e, 0x58, 0xc9, 0x58, 0xeb, 0x45, 0x66, 0x25, 0x63, 0xaf,
	0x0d, 0xb6, 0x11, 0x47, 0xcb, 0x39, 0xe1, 0x21, 0x14, 0xd5, 0x72, 0x4e, 0x7a, 0xc1, 0xe9, 0xd8,
	0xd9, 0xb5, 0xf6, 0x4a, 0x62, 0x5a, 0xf0, 0x6e, 0xa0, 0x32, 0x8c, 0x96, 0x33, 0x1e, 0x8d, 0xbf,
	0x5b, 0x6d, 0x58, 0xeb, 0x27, 0xd6, 0x83, 0x72, 0xa8, 0x22, 0xb5, 0x90, 0xd8, 0x84, 0x8a, 0x5c,
	0xc4, 0x31, 0x49, 0xa9, 0xf9, 0x2a, 0x5b, 0x8f, 0xa7, 0x67, 0x50, 0xd4, 0x41, 0xea, 0x50, 0x0d,
	0x47, 0xfe, 0x20, 0xf0, 0x59, 0xe0, 0xee, 0xa0, 0x0d, 0x95, 0x21, 0xbb, 0xeb, 0xf7, 0x1e, 0xfb,
	0x6e, 0x01, 0x6b, 0x50, 0xf2, 0x83, 0x7e, 0x6f, 0xe0, 0x5a, 0x9d, 0x77, 0x0b, 0x9c, 0x30, 0x2b,
	0x26, 0x24, 0xf1, 0x96, 0xc4, 0x84, 0xb7, 0xb0, 0xf7, 0x40, 0x6a, 0xf3, 0xc3, 0xf7, 0x82, 0xbf,
	0xea, 0x8a, 0x10, 0xd7, 0x81, 0xf2, 0xc2, 0x5a, 0xae, 0x79, 0xcb, 0xfb, 0xf1, 0x61, 0x3f, 0xc7,
	0x57, 0x49, 0x7e, 0x37, 0xc0, 0xaf, 0x06, 0x3a, 0xfa, 0x25, 0xd8, 0x5d, 0x41, 0x91, 0xa2, 0x0c,
	0x73, 0xcc, 0x8a, 0xa9, 0xad, 0xb5, 0xc5, 0x06, 0xaf, 0xa1, 0xce, 0xe8, 0x59, 0x90, 0x9c, 0xfc,
	0x7d, 0xea, 0x33, 0x77, 0x01, 0x76, 0x40, 0x33, 0x5a, 0x9f, 0xda, 0x86, 0x35, 0xcc, 0x9b, 0x69,
	0xfe, 0x1c, 0xa0, 0x3b, 0xa1, 0x78, 0xfa, 0x5f, 0xe0, 0xa9, 0xac, 0xa7, 0xab, 0x8f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x82, 0x73, 0x00, 0x43, 0x81, 0x02, 0x00, 0x00,
}
